# Generated by Django 4.2.2 on 2025-05-19 12:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('report_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('report_type', models.IntegerField(choices=[(0, 'Donation Summary'), (1, 'Inventory Status'), (2, 'Order Summary'), (3, 'Delivery Efficiency'), (4, 'User Activity')], default=0)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('data', models.JSONField()),
                ('generated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
