# Generated by Django 5.2.1 on 2025-05-24 14:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='batch_key',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='reports',
            name='report_type',
            field=models.IntegerField(choices=[(1, 'Inventory Status'), (2, 'Order Summary'), (3, 'Delivery Efficiency'), (4, 'User Activity')], default=1),
        ),
    ]
