# Generated by Django 4.2.2 on 2025-05-19 12:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('contact_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('vehicle', models.TextField()),
                ('login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Deliveries',
            fields=[
                ('delivery_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pickup_time', models.DateTimeField(default=datetime.datetime.now)),
                ('delivery_time', models.DateTimeField()),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'In Transit'), (2, 'Delivered'), (3, 'Failed')], default=0)),
                ('driver_id', models.ForeignKey(db_column='driver_id', on_delete=django.db.models.deletion.CASCADE, to='Drivers.driver')),
            ],
        ),
    ]
