# Generated by Django 5.2.1 on 2025-05-24 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drivers', '0003_alter_driver_login_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveries',
            name='driver_id',
            field=models.ForeignKey(db_column='driver_id', on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='Drivers.driver'),
        ),
    ]
