# Generated by Django 5.2.1 on 2025-05-24 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drivers', '0004_alter_deliveries_driver_id'),
        ('NGO', '0004_alter_orders_inventory_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveries',
            name='order_id',
            field=models.OneToOneField(db_column='order_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='NGO.orders'),
        ),
    ]
