# Generated by Django 5.2.1 on 2025-05-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drivers', '0005_deliveries_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveries',
            name='delivery_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveries',
            name='pickup_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
