# Generated by Django 4.2.2 on 2025-05-19 12:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Drivers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('donor_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('contact_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('address', models.TextField(blank=True, null=True)),
                ('login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventory_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('food_type', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('expiration_date', models.DateField()),
                ('status', models.SmallIntegerField(choices=[(0, 'Available'), (1, 'Reserved'), (2, 'Expired')], default=0)),
                ('donor_id', models.ForeignKey(db_column='donor_id', on_delete=django.db.models.deletion.CASCADE, to='Donors.donor')),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('donation_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('donation_time', models.DateTimeField(default=datetime.datetime.now)),
                ('delivery_id', models.ForeignKey(db_column='delivery_id', on_delete=django.db.models.deletion.CASCADE, to='Drivers.deliveries')),
            ],
        ),
    ]
