# Generated by Django 4.2.2 on 2025-05-19 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Donors', '0001_initial'),
        ('NGO', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='order_id',
            field=models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, to='NGO.orders'),
        ),
    ]
