# Generated by Django 5.2.1 on 2025-05-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donors', '0004_alter_donor_login_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='food_type',
            field=models.SmallIntegerField(choices=[(0, 'Packed'), (1, 'Non-packed')], default=0),
        ),
    ]
