# Generated by Django 5.2.1 on 2025-05-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donors', '0005_alter_inventory_food_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='food_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
