# Generated by Django 5.2.1 on 2025-05-23 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Donors', '0006_inventory_food_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='food_name',
            new_name='item_name',
        ),
    ]
