# Generated by Django 5.2.1 on 2025-05-24 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donors', '0007_rename_food_name_inventory_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='donor_id',
            field=models.ForeignKey(db_column='donor_id', on_delete=django.db.models.deletion.CASCADE, related_name='donor', to='Donors.donor'),
        ),
    ]
