# Generated by Django 5.2.1 on 2025-05-24 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Donors', '0008_alter_inventory_donor_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donation',
        ),
    ]
