# Generated by Django 4.2.2 on 2025-05-19 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Donors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NGO',
            fields=[
                ('ngo_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('organization_name', models.CharField(max_length=150)),
                ('contact_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('address', models.TextField(blank=True, null=True)),
                ('login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('status', models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Delivered'), (3, 'Cancelled')], default=0)),
                ('inventory_id', models.ForeignKey(db_column='inventory_id', on_delete=django.db.models.deletion.CASCADE, to='Donors.inventory')),
                ('ngo_id', models.ForeignKey(db_column='ngo_id', on_delete=django.db.models.deletion.CASCADE, to='NGO.ngo')),
            ],
        ),
    ]
