# Generated by Django 5.2.1 on 2025-05-24 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donors', '0007_rename_food_name_inventory_item_name'),
        ('NGO', '0003_alter_ngo_login_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='inventory_id',
            field=models.ForeignKey(db_column='inventory_id', on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='Donors.inventory'),
        ),
    ]
