# Generated by Django 5.2.1 on 2025-05-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0004_alter_orders_inventory_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Delivered'), (3, 'Cancelled'), (4, 'Failed')], default=0),
        ),
    ]
