# Generated by Django 5.2.1 on 2025-05-24 15:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0005_alter_orders_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
